[package]
name = "problem"
version = "1.1.0"
authors = ["Jakub Pastuszek <jpastuszek@protonmail.com>"]
description = "Error handling for command line applications"
build = "build.rs"
repository = "https://github.com/jpastuszek/problem"
readme = "README.md"
keywords = ["error"]
categories = ["command-line-interface"]
license = "MIT"

[features]
default = ["log-panic", "backtrace"]
log-panic = ["log"]

[dependencies]
log = { version = "0.4.3", optional = true }
backtrace = { version = "0.3.13", optional = true }

[build-dependencies]
skeptic = "0.13.3"

[dev-dependencies]
skeptic = "0.13.3"
